language: python
env:
  - TOXENV=py27
  - TOXENV=pypy
  - TOXENV=py27-trunkdeps
matrix:
  allow_failures:
    - env: TOXENV=pypy
    - env: TOXENV=py27-trunkdeps
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
